services:

  app:
    build: .
    container_name: handwerk-ai
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: ai-agent-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_agent
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: